# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'UIViewDraggableDemo' do

end

target 'UIViewDraggableDemoTests' do
	pod 'FBSnapshotTestCase'
	pod 'Expecta+Snapshots'
	pod 'Specta'
	pod 'Expecta'
	pod 'OCMock'
	pod 'OCMockito'
end

