source 'https://github.com/CocoaPods/Specs.git'

target 'UIViewDraggableDemo' do
  pod 'UIView+draggable', path: '../'
end

target 'UIViewDraggableDemoTests' do
  pod 'UIView+draggable', path: '../'
  pod 'Specta', '1.0.5'
  pod 'Expecta', '1.0.5'
  pod 'Expecta+Snapshots', '3.0.0'
  pod 'OCMock', '3.2'
  pod 'OCMockito'
end

